dist: trusty
sudo: required
language: node_js
node_js:
    - '10'
    - '8'
services:
    - mysql
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS mysqldump_test;'
install: yarn
script:
    - yarn format-check
    - yarn typecheck
    - yarn lint
    - yarn build
    - yarn setup-travis
    - yarn test
    - yarn test-prod
